d_rats/map/__init__.py, d_rats/map/mapdisplay.py, d_rats/map/mapwidget.py, d_rats/map/mapwindow.py
d_rats/map/__init__py:
Expose MapWindow and MapWidget classes.
d_rats/mapdisplay.py:
Convert to Gtk.Application.
d_rats/mapwidget.py:
Skeleton class for MapWidget.
d_rats/MapWindow.py:
Skeleton class for MapWindow
=> Convert MapDisplay to Gtk.Application

d_rats/map/mapbottompanel.py, d_rats/map/mapstatusbox.py, d_rats/map/mapwidget.py, d_rats/map/mapwindow.py
d_rats/map/bottompanel.py:
Make controls visible.
Fix orientation of zoom control.
d_rats/map/mapstatusbox.py:
Make text for progress bar visible.
d_rats/map/mapwidget.py:
Add MapLocation class.
Add code to help test the controls.
=> Setting up the Map Controls

d_rats/map/mapdraw.py
Need to have the scale positioning be based on
the tile size, the pango layout size, and the
size of the possible scrollbars.
This gets rid of most of the use of "Magic" numbers
in determining the scrollbar position.
=> Fix scale positioning

d_rats/miscwidgets.py
Minor Docstring fixes.
Fix make_pixbuf_choice routine.
=> Fix GdkPixbuf handling in miscwidgets

d_rats/utils.py
Mostly converted to use logging instead of printlog
Fix gettext import
in get_icon_from_map, force vertical offset to be an integer
In get_icon: Initialize APRS icons if needed.
=> Fix utils.py icon lookup

d_rats/ui/main_events.py
Fix up gettext setup.
Convert to use logging module.
Fix to raise a specific exception on error.
In EventTab fix bug in adjustment querying.
=> main_events fixes

d_rats/comm.py
Fix SocketDataPath.readline() for python 3.
=> comm mdoule Python3 fixes

d_rats/sessions/base.py
d_rats/sessions/base.py:
Minor correction to Docstring.
=> sessions/base Docstring update

d_rats/sessions/rpc.py
Resolve some pylint issues.
Restrict RPC jobs to known jobs (security fix).
decode_dict(): Fix python3 support.
worker(): Fix dict race issue.
=> rpc.py python3 fixes

d_rats/sessions/chat.py
d_rats/sessions/chat.py:
Add copyright.
Python3 bytes/str conversions.
=> sessions/chat Python3 fixes

d_rats/sessions/file.py
Fix partial file transfers save/restore
=> d_rats/sessions/file.py:

d_rats/sessions/file.py, d_rats/sessions/form.py
d_rats/sessions/file.py:
Add standard copyright message.
d_rats/sessions/form.py:
Add standard copyright message.
Convert to use logging module.
=> Minor sessions file/form fixes

d_rats/sessions/sniff.py
d_rats/sessions/sniff.py:
Add copyright.
Python3 bytes/str conversions.
=> sniff python3 fixes

d_rats/sessions/sock.py
d_rats/sessions/sock.py:
Add copyright.
=> sock python fixes

d_rats/sessions/stateful.py
d_rats/sessions/stateful.py:
Python3 bytes/str conversions.
=> stateful python fixes

d_rats/utils.py
Fix hexprintlog() for bytes type
fix port_for_station() to tolerate threads modifying dictionaries.
=> utils.py python3 fixes

d_rats/miscwidgets.py
=> miscwidgets dictionary thread fix

d_rats/msgrouting.py
d_rats/msgrouting.py:
Fix to raise specific exceptions
=> msgrouting python3 fixes

d_rats/session_coordinator.py
d_rats/session_coordinator.py:
Fix to raise specific exceptions
In status_cb() avoid divide by zero error if on a fast network.
=> session_coordinator python3 fixes

d_rats/sessionmgr.py
d_rats/session_coordinator.py:
Removed a broad-exception.
Improved a Docstring.
=> sessionmgr fixes

d_rats/transport.py
d_rats/transport.py:
Add some optional debugging code
=> transport fixes

d_rats/ui/main_chat.py
d_rats/main_chat.py:
Fix dictionary iterations.
Comment out a diagnostic print statement.
=> main_chat fixes

d_rats/ui/main_files.py
d_rats/main_files.py:
Fix dictionary iterations.
=> main_files fixes

d_rats/ui/main_stations.py
d_rats/main_stations.py:
Improved a Docstring.
In saw_station: force some parameters to be str type.
=> main_stations fixes

locale/it/LC_MESSAGES/D-RATS.po
locale/it/LC_MESSAGES/D-RATS.po:
Translation updates from Maurizio Andreotti.
=> Update D-RATS italian translation po file

d_rats/signals.py
d_rats/signals.py:
Add module title docstring wanted by pylint.
=> signals minor documentation fix.

d_rats/msgrouting.py
d_rats/msgrouting.py:
Fix bad indent flagged by pylint.
Supress pylint global message for now.
=> msgrouting pylint fixes

d-rats_repeater.py
d_rats_repeater.py:
fixed some broad-exceptions to be specific exceptions.
Fix password negotiation for python3.
Replace deprecated optparse module with argparse.
=> d-rats_repeater python3 fixes

d_rats/gps.py
d_rats/gps.py:
Fixed some broad-exceptions to be specific exceptions.
Fixed self test data to pass.
Python3 byte to str conversion.
=> gps python3 fixes

build_pot.sh, d_rats/dplatform.py
build_pot.sh:
Minor comment fixup.
Minor comment fixup.
=> Minor Comment fixes

d_rats/mainapp.py, d_rats/map/mapdisplay.py, d_rats/map/mapdraw.py, d_rats/map/mapmarkerlist.py, d_rats/map/maptile.py, d_rats/map/mapwidget.py, d_rats/map/mapwindow.py, d_rats/map/mapzoomcontrols.py, d_rats/map_sources.py, d_rats/miscwidgets.py
Added the code to actually start plotting points.
Some of the menu items for acting on points are still not implemented.
Temporarily disable USGS and NBDC Map sources.
Add test of loading map overlays.
Add draw_cross_marker_at method.
Add draw_image_at method.
Implement draw_marker method.
Add draw_text_marker_at method.
Add set_zoom_changed method.
d_rats/map/mapmarkerlist.py:
Implement rendering the stored lists.
Implement recenter callback method.
Add a Unit test.
Rename axis to tile in variable names
Add some assistance with calculating the map fudge factor.
d_rats/map/mapwidget.py:
Attempt to fix Map fudge calculations.
Implement point_is_visible method.
Add the …
=> Starting to plot points

d_rats/mainapp.py, d_rats/map/mapdisplay.py, d_rats/map/mapwindow.py, d_rats/version.py
Make sure is compatible with new map methods.
Minor optimization.
Add Thunderforest information to Map Unit test.
Minor fixups.
Add Thunderforest required copyright notice.
Fix minor spelling error.
=> Add thunderforest maps to unit test

d_rats/geocode_ui.py
d_rats/geocode_ui.py:
Fix python2 compatibility
=> Fix geocode_ui python2 compatibility

d_rats/mainwindow.py
Fix do_conninet and do_showpane for python3.
=> mainwindow show_station fix

d_rats/map/mapwindow.py
This was meant to be in the previous commit.
Implement the Info Window mouse popup for points.
Shorten the mouse movement timer from 10 to 5 to be more responsive.
=> Actually add Info Window

d_rats/map/mapwindow.py, d_rats/map/markereditdialog.py
Remove commented do_address internal method()
d_rats/map/markereditdialog.py:
Enable Geocode address lookup if available
=> feat(map): Enable Geocode address lookup

d_rats/map/maptile.py
Improve Exception Handling by properly logging when
both a tile is not found, or an SSl Certificate does not validate.
=> fix(map): Improve Exception Handling

d_rats/spell.py
issue: wb8tyw-65
d_rats/spell.py:
Fix incorrect Pango constant.
Add test for failed method to unit test.
=> fix(spell) Gtk Pango fixes for spell

d_rats/map/maptile.py
wb8tyw_issue: 64
Fix incorrect name for _map_key variable.
=> fix(map): Fix map url map_key

d_rats/ui/main_files.py
In FileView class, make sure that the download directory exists.
In RemoteFileView._file_list_cb, make sure unit_str is of str type.
=> fix(files): File download upload fixes

d_rats/map/mapwindow.py, d_rats/map/markereditdialog.py, d_rats/map/markerpopupmodel.py, d_rats/map_sources.py
Enable the remaining map menu items.
Minor cleanup to some exception handling.
Complete marker_center_handler, marker_delete_handler,
marker_edit_handler methods.
d_rats/map/markereditdialog.py:
Fix methods for GTK-3 differences.
d_rats/map/markerpopupmodel.py:
Remove diagnostics.
Remove some diagnostics.
Take a pass at cleaning up broad exceptions.
=> fix(map): Enable Menu actions

d_rats/map/mapmenumodel.py, d_rats/map/mapwindow.py
d_rats/map/mapmenumodel.py:
Add Accelerators for Printable Visible and Save Visible.
Add application as a property of the MapWindow.
=> fix(map): Add Menu Accelerators

d_rats/map/mapdisplay.py, d_rats/map_source_editor.py, d_rats/map_sources.py, d_rats/version.py, ui/mainwindow.glade
Re-enable USGS River Sources and NBDC Buoy Source
d_rats/map_source_editor.py
Add some DocStrings.
Fix editor to save changes.
Fix handling empty river site list.
Change the URL format for looking up sites.
Fix parsing of the downloaded data.
Add attribution for using USGS data.
=> fix(map): Map Source Editor USGS fix

d_rats/cap.py
d_rats/cap.py:
Conversion to lmxl current Weather service CAP data.
Remove python2 support.
Get Unit test working.
=> fix(cap): Convert CAP module to python3/lxml

d_rats/dplatform.py, d_rats/qst.py, d_rats/version.py
Convert UnixPlatform.run_sync method to python 3.
d_rats/qst.py:
in do_dprs_calculator module fix data size check.
in QSTWX.do_qst, log when qst not sent.
Fix QSTOpenWeather class for python 3.
Add required attribution for using OpenWeather API data.
=> fix(qst): Fix QST code for python3

d_rats/ui/main_chat.py
This is a documentation only commit
=> doc(chat): Improve Docstrings for main_chat.py

d_rats/ui/main_chat.py
Move scrolling into a display-changed handler
=> fix(chat): Chat scrolling fix attempt

d_rats/map/maptile.py
In fetch_url(), catch OSEerror as expected errors.
=> fix(map): Handle Map fetching errors better

d_rats/dplatform.py, d_rats/mainapp.py, d_rats/mainwindow.py
Fix default source_dir setting.
d_rats/mainap.py:
Remove uneeded comment
Minor change to unit test to match dplaform fix.
=> fix:(dplatform) Allow run from anywhere

d_rats/comm.py, d_rats/ddt2.py, d_rats/transport.py
Store the connection name to improve logging.
Fix exception handling.
d_rats/ddt2.py:
Fix exception handling.
d_rats/transport.py:
Fix and exception handling.
Improve logging.
Implement automatic reconnection to broken connections.
=> fix:(comm) Socket Connection fixes

setup.py
Correcting the branch for a simple PR.
=> Add map module to Linux installation

setup.py
setup.py:
First pass getting pylint issues resolved.
=> fix(setup): Pylint style fixes

d_rats/agw.py, d_rats/comm.py, d_rats/config.py, d_rats/emailgw.py, d_rats/inputdialog.py, d_rats/map_sources.py, d_rats/miscwidgets.py, d_rats/qst.py, d_rats/sessionmgr.py, d_rats/spell.py, d_rats/ui/conntest.py, d_rats/ui/main_chat.py, d_rats/ui/main_events.py, d_rats/ui/main_stations.py, d_rats/wl2k.py
Now that documentation can be generated, fix up many of the
issues that were found.
Files updated:
d_rats/agw.py
d_rats/comm.py
d_rats/config.py
d_rats/emailgw.py
d_rats/inputdialog.py
d_rats/map_sources.py
d_rats/miscwidgets.py
d_rats/qst.py
d_rats/sessionmgr.py
d_rats/spell.py
d_rats/ui/conntest.py
d_rats/ui/main_chat.py
d_rats/ui/main_events.py
d_rats/ui/main_stations.py
d_rats/wl2k.py
=> doc: Fix issues with DocStrings

d_rats/mailsrv.py
d_rats/mailsrv.py:
Fix most of the pylint issues.
Add Docstrings.
=> fix(mailsrv): Pylint / Docstrings for mail server

d_rats/config.py, d_rats/emailgw.py, d_rats/formgui.py, d_rats/miscwidgets.py, d_rats/ui/main_messages.py
First pass at handling buttons with nothing to do.
d_rats/emailgw.py:
Fix dummy e-mail domain example.com per standard.
Fix bytes to/from string issues.
Fix "UNKNOWN" recipient issue when only e-mail address known.
Convert GObject.idle_add to GLib.idle_add.
Don't delete message from mail server before attempting
to convert it to a d-rats message.
d_rats/formgui.py:
Minor Docstring fix.
remove a broad exception.
Remove a broad exception.
=> fix(emailgw): Fix pop3 to mail/chat

d-rats_repeater.py
d-rats_repeater.py:
Remove python2 compatible code.
Remove unused code.
Fix "unsafe" eval calls.
=> fix(repeater) Ratflector cleanup

d_rats/qst.py
d_rats/qst.py:
Missed a change on the previous gps routine refactor.
Signed-off-by: John E. Malmberg <wb8tyw@gmail.com>
=> fix(qst): Fix invalid symbol

d_rats/yencode.py
d_rats.yencode.py:
Fix copyright notice
Minor Docstring fixes
=> fix(yencode): Docstring fixes

d_rats/qst.py, d_rats/wu.py
d_rats/qsl.py:
Comment out rest of accesses to non-functional wu module.
d_rats/wu.py: (incomplete/unused)
This module looks incomplete and can not be tested.
It was accessed, but not used by the qst module.
Leaving it in for now incase someone wants to debug/complete it.
Fix up pylint and Docstring issues.
=> fix(qst): The wu module is not done

d_rats/pluginsrv.py
d_rats/pluginsrv.py:
Remove python 2 compatibility.
Restore use of fixed port.
Raise named exceptions.
Replace "insecure" eval call.
=> fix(pluginsrv): Python3 Conversion

d_rats/mainapp.py
Pluginsrv fail to start should not be fatal.
Remove python2 compatibility.
Fix some broad exceptions to be named exceptions.
=> fix(mainapp): Pluginsrv fail not fatal

d_rats/version.py
Fix internationalization.
Remove last pylint diagnostic
Make HTTP_CLIENT_HEADERS message debug level.
=> fix(version): Version fixes

plugin_test.py
plugin_text.py:
Fix bad Docstring.
=> fix(doc): Minor fix for plugin_test

d_rats/inputdialog.py
d_rats/inputdialog.py:
Fix internationalization.
=> fix(inputdialog): Input Dialog module

d_rats/geocode_ui.py
d_rats/geocode_ui.py:
Fix internationalizaion.
Remove some python2 compatibility code.
=> fix(geocode_ui): Geocode UI mdodule

d_rats/config_tips.py
d_rats/config_tips.py:
Fix internationalization.
=> fix(config): Fix config_tips

d_rats/ui/conntest.py
d_rats/ui/conntest.py:
Fix internationalization.
Resolve all but 2 pylint issues.
=> fix(conntest): fix conntest

d_rats/ddt2.py
=> fix(ddt2): Docstring fixups

d_rats/transport.py
d_rats/transport.py:
Improve docstrings
Code cleanup
=> fix(transport): Documentation string

d_rats/session_coordinator.py
d_rats/session_coordinator.py:
Improve Docstring
Code cleanup
=> fix(session_coordinator): Docstring fixup.

d-rats.py
d-rats.py:
Code cleanup.
Restore override of default exception handler.
=> fix(d-rats): Code cleanup

d_rats/mainapp.py, d_rats/sessionmgr.py, d_rats/wl2k.py
Just some general cleanup and documentation improvements.
Use unique global variable for module level logger
Fix a number of pylint issues.
Fix a most of the broad exceptions.
=> fix(mainapp): cleanup of mainapp

d_rats/sessionmgr.py, d_rats/sessions/chat.py, d_rats/sessions/file.py, d_rats/sessions/form.py, d_rats/sessions/rpc.py, d_rats/sessions/sock.py, d_rats/sessions/stateful.py, d_rats/station_status.py, d_rats/transport.py, d_rats/ui/main_chat.py, d_rats/ui/main_messages.py, d_rats/utils.py
d_rats/sessionmgr.py:
d_rats/sessions/chat.py:
d_rats/sessions/file.py:
d_rats/sessions/form.py:
d_rats/sessions/sock.py:
d_rats/sessions/stateful.py:
d_rats/station_status.py:
d_rats/transport.py:
=> fix(documentation) Docstring update

d_rats/comm.py
Fix kwargs handling for Serial class.
Remove python2 compatibility code.
Improve DocStrings
=> fix(comms): Minor Serial fixes

d_rats/emailgw.py
d_rats/emailgw.py:
DocString improvements.
=> fix(emailgw): DocString improvements

d_rats/gps.py
d_rats/gps.py:
DocString fixes
Fix local method naming for python compliance.
=> fix(gps) DocString fixes

d_rats/mainapp.py
DocString fixes.
Fix some variable names for readability.
Signed-off-by: John E. Malmberg <wb8tyw@gmail.com>
=> fix(mainapp) DocString fixes

d_rats/msgrouting.py
d_rats/msgrouting.py:
Minor refactoring / spelling fixes.
=> fix(msgrouting): DocString improvements

d_rats/map_sources.py, d_rats/wl2k.py
Fix spelling error.
Fix spelling errors.
=> fix(doc) Fix spelling

d_rats/map/mapwindow.py, d_rats/ui/main_chat.py, d_rats/ui/main_events.py, d_rats/ui/main_files.py
Spelling fixes in comments.
Improve Docstrings and comments.
Spelling fixes.
Group IDs are actually group name strings.
Improve Docstrings, spelling fixes.
=> fix(doc) Spelling

d_rats/miscwidgets.py
Fix Spelling.
Document currently unused routines.
=> fix(miscwidgets): DocString and Spelling

d_rats/ui/main_messages.py
=> fix(main_messages): code cleanup

d_rats/mainwindow.py
Rename methods as "do_" methods are virtual overrides for GTK methods
and we want those to stand out.
=> fix(mainwindow): Code cleanup

d-rats_repeater.py
d-rats_repeater.py:
Fix warmup_transport to use configured value.
Python3 convention fixes.
Improve Docstring.
=> fix(repeater): Code cleanup

d_rats/formbuilder.py, d_rats/formgui.py, d_rats/miscwidgets.py
d_rats/formbuilder.py:
Code Cleanup to be closer to current Python conventions.
d_rats/formgui.py:
Fix Docstring.
Fix Docstring.
=> fix(formbuilder): Code cleanup

d-rats_repeater.py
d-rats_repeater.py:
Skip ports that require a call if default call not changed.
Add tnc-ax25 radio port variant.
Add dongle radio port.
Add AGWPE radio port.
=> fix(repeater) Add radio port types

d_rats/mainapp.py
Need to move some code around to make it compliant with
the Gtk.Application class requirements.
=> fix(mainapp): GtkApplication fixes

d_rats/config.py
Code Cleanup to be closer to current Python conventions.
Spellcheck fixes.
=> fix(config) Code cleanup

d_rats/ui/main_common.py, d_rats/ui/main_messages.py, d_rats/ui/message_folders.py, d_rats/ui/message_list.py, d_rats/ui/message_popup_model.py, d_rats/ui/test_message_popup_model.py
Get the folder menu working with the new API
d_rats/ui/main_common.py:
In prompt_for_message, retrieve data before destroying it.
Need to pass ApplicationWindow object to MessageFolders.
d_rats/ui/message_folders.py:
Convert to Gio.Actions and Gio.Menu.
d_rats/ui/message_list.py:
Fix pylint issue with too many lines in function.
d_rats/ui/message_popup_model.py:
New module to implement popup menu model.
d_rats/ui/test_message_popup_model.py:
Test module for message_popup_model.py
=> fix(main_messages): Folder Menu working

d_rats/mainwindow.py, d_rats/ui/event_tab.py, d_rats/ui/main_events.py
d_rats/ui/event_tab.py:
New module wtih existing EventTab class.
Gtk.UIManager does not work with GTK-3
EventTab is now in d_rats.ui.event_tab.
Remove EventTab class.
=> fix(main_event): Code Cleanup

d_rats/miscwidgets.py
Convert the toggle handlers to Gtk3 documented syntax.
=> fix(miscwidget): Fix toggle handlers

d_rats/config.py
Fix parameters for item-toggled handler to match emitted signal.
=> fix(config): Fix config radio toggle

d_rats/config.py, d_rats/dratsexception.py, d_rats/miscwidgets.py
Handle exception that will happen during normal user entry for the
times that the GPS coordinates do not happen to validate.
Handle LatLonEntryException for GPS entry.
d_rats/dratsexception.py:
Move LatLonException classes to this module.
Move LatLonException to d_rats/dratsexception.py
=> fix(config): User GPS entry

d_rats/ui/event_tab.py
d_rats/ui/event_tab.py:
Add TreeModelSorted object needed for Gtk3.
Fix config storage of sort state for current ConfigParser API.
Set self.filter to be self._filter a private attribute.
Move logging to be a class variable.
=> fix(main_event): Fix Event sorting

d_rats/mainapp.py
The map server needs to send a bytes object for python 3.
Fix to send a bytes object to the map server.
Map server connection errors should not be fatal to d-rats.
=> fix(mainapp): Map server fixes

.github/workflows/pylint.yml, tests/install_pylint_ubuntu.sh
.github/workflows/pylint.yml:
Pylint action for github
tests/install_pylint_ubunut.sh:
Script to make sure pylint is installed on Ubuntu
=> test(pylint) Add pylint github action

.github/workflows/shellcheck.yml, tests/install_shellcheck_ubuntu.sh, tests/pre-commit_d/shellcheck_check.sh
.github/workflows/shellcheck.yml: (new)
Start a workflow to check shell scripts.
tests/install_pylint_ubuntu.sh:
Missing install of file package.
tests/install_shellcheck_ubuntu.sh: (new)
Make sure shellcheck is installed for github action.
tests/pre-commit_d/shellcheck_check.sh: (new)
Shellcheck check for pre-commit and github action.
=> test(shellcheck): Add shellcheck to linting

.github/workflows/codespell.yml, README.md, tests/pre-commit_d/codespell_check.sh, tests/pre-commit_d/shellcheck_check.sh
This adds Codespell checking for both a git pre-commit hook and
also as a github action.
.github/workflows/codespell.yml: (new)
Github action to run codespell
README.md:
Update to include codespell
tests/pre-commit_d/codespell_check.sh (new)
Precommit hook for codespell
tests/pre-commit_d/shellcheck_check.sh:
Minor enhancement for using newer shellcheck versions.
=> test(codespell) Add Codespell checking

.github/workflows/codespell.yml, .github/workflows/pylint.yml, .github/workflows/shellcheck.yml, .github/workflows/xmllint.yml, .github/workflows/yamllint.yml, README.md, tests/pre-commit_d/yamllint_check.sh
.github/workflows/yamllint.yml: (new)
Github action for checking yaml.
tests/pre-commit_d/yamllint_check.sh: (new)
Git hook to checking yaml.
.github/workflows/codespell.yml:
.github/workflows/pylint.yml:
.github/workflows/shellcheck.yml:
.github/workflows/xmllint.yml:
Fixed to pass yamllint scan.
README.md:
add yamllint to list of development packages.
=> fix(yamllint) Add yamllint checking
