- d_rats/map/__init__.py
- d_rats/map/mapbottompanel.py
- d_rats/map/mapmarkerlist.py
- d_rats/map/mapstatusbox.py
- d_rats/map/mapwidget.py
- d_rats/map/mapwindow.py
- d_rats/map/mapzoomcontrols.py
Add MapBottomPanel, MapMarkerList, MapStatusBox, and MapZoomControls.
d_rats/map/mapbottompanel.py:
Classes for the Map Bottom Panel.
d_rats/map/mapmarkerlist.py:
Class for Map Marker List.
d_rats/map/mapstatusbox.py:
Class for Map Status Box.
d_rats/map/mapwidget.py;
Minor fixes.
Remove code for constructing MapBottomPanel, MapMarkerList,
MapStatusBox, and MapZoomControls
d_rats/map/mapzoomcontrols.py:
Class for Map Zoom Controls
> Refactor Map modules and classes

- d_rats/map/__init__.py
- d_rats/map/mapbottompanel.py
- d_rats/map/mapmarkerlist.py
- d_rats/map/mapmenumodel.py
- d_rats/map/mapwindow.py
Add the Map menu with the functions stubbed out.
New MapMenuModel class.
d_rats/map/mapbottompanel.py:
d_rats/map/markerlist.py:
Minor documentation fixes.
d_rats/map/mapmenumodule.py:
Class for creating the Map menu and associated actions.
Move the Map Menu into its own class and add the handlers.
Add stub routines for the current public methods for mapwindow.
> Adding the Map Menu

- d_rats/map/__init__.py
- d_rats/map/mapdisplay.py
- d_rats/map/mapdraw.py
- d_rats/map/mapwidget.py
- d_rats/map/mapwindow.py
- d_rats/map/mapzoomcontrols.py
Add MapDraw class.
Temporarily add methods called by mainapp.
Move creating the pango layout info MapWidget.
Move creating the constant Gdk color black into mapwidget.
d_rats/map/mapwidget.pylint
Refactor to create map_scale_pango_layout as a simplification
Add calculate_bounds method
Add methods to be called by mainapp replacing calls to mapdisplay.
d_rats/map/mapzoomcontrols.py:
Copy zoom setting into MapTile class
> Connect lat,lon, and zoom to map

- d_rats/map/__init__.py
- d_rats/map/mapdraw.py
- d_rats/map/mapexception.py
- d_rats/map/maptile.py
- d_rats/map/mapwindow.py
Add MapException class.
Minor fix to LoadContext/fraction property.
Remove commented out code that will not be used.
Fix progress to report % of tiles that were successfully downloaded.
Fix exception handling for cairo errors.
Enable threaded Tile Fetch.
d_rats/map/mapexception.py:
Base Map Exception class.
Add class methods to store formerly global values.
Add fetch_url method and enable fetching.
Store map_widget reference in MapTile class.
Remove test code from refresh_item_handler.
d_rats/map/mapzoomcontrols.py:
Improved fix for over sensitive zoom slider control
Store zoom level in MapTile class
> Make map downloading operational

- d_rats/map/mapdraw.py
- d_rats/map/mapmenumodel.py
- d_rats/map/mapwidget.py
- d_rats/map/mapwindow.py
- d_rats/map/mapzoomcontrols.py
Enable the print and save functions for the visible map.
Add code to set scrollbars to the center of the screen when needed.
d_rats/map/mapmenumodel.py:
Disable the print and save entire map entries as there does not
seem to be a good way to implement them.
d_rats/map/mapwidget.py:
Remove some unused code.
Add center_on method to let MqpDraw class know to center the scroll bar.
Add export_to method for saving the visible screen to a file.
d_rats/map/mapwidget.py:
Rename menu handler methods to allow alphabetical grouping.
Add get_visible_bounds() method.
Add printable_map and save_map related methods.
d_rats/map/MapZoomControls.py:
Improve Zoom level setting.
> Enable Map print and save options

- d_rats/map/__init__.py
- d_rats/map/mappopupmodel.py
- d_rats/map/mapwidget.py
- d_rats/map/mapwindow.py
Add in a stubbed out mouse popup menu.
Add mappopupmodel class.
d_rats/map/mappopupmodel.py:
Popup menu for the mouse pointer
d_rats/map/mapwidget.py:
The scroll adjustments have no value until being
exposed, so can only be queried in the expose handler.
Connect existing map_source_editor for testing
Add the popup menu for the mouse.
Make mouse movement more sensitive.
> Add Mouse Popup Menu

- d_rats/ddt2.py
Need to make sure that the d_station and s_station are of type str
or it causes them to be auto converted from bytes type with a "b" prefix.
d_rats/ddt2.py:
Converted to use logging module
Fix str->bytes conversions to use "utf-8" for consistency
Need to make sure that the d_station and s_station are type str
> ddt2 Python3 fixes

- d_rats/dplatform.py
Tolerate pywnitypes import failing needed to work around
bug in msys2 mingw64 pytho that was fixed.
Handle Windows exceptions instead of broad exceptions.
Fix to use win32api for getting version info.
> dplatform win fixes

- d_rats/geocode_ui.py
geopy is not available as a signed package on all
plaforms that I can test on.
Nothing in d-rats should require a module installed
from pypi via pip.
d_rats/geocode_ui.py:
Handle python2 import failure while we still
have python2 compatibility.
> make geocode_ui geopy optional for python2

- d-rats.py
- d-rats_repeater.py
d_rats.py:
Replace deprecated optparse module with argparse.
d_rats_repeater.py:
Fix typo in copyright date.
> d_rats.py python3 fixes

- d_rats/mainapp.py
- d_rats/mainwindow.py
- d_rats/map/mapdisplay.py
- d_rats/map/mapwindow.py
Convert MainApp to be Gtk.Application.
Add shutdown handlers and temporary diagnostics.
Need access to application object for exit handling.
Fix shutdown handlers and add temporary diagnostics.
Unit test needs to tell map to exit when done.
Add the map shutdown handlers.
Add methods needed by MainApp.
Add a flag to indicate when map should be shutdown.
> Start conversion to new map modules

- d_rats/gps.py
- d_rats/mainapp.py
It just seemed wrong to report a station of  "UNKNOWN" when logging an incoming
GPS position from a known station.
d_rats/gps.py:
Make default of _('UNKNOWN') consistent.
Allow a StaticGPSSource to specify an optional callsign
__incoming_gps_fix: Add station callsign to logged response.
> Minor gps logging fix

- d_rats/map/mapdraw.py
- d_rats/map/maptile.py
- d_rats/map/mapwidget.py
- d_rats/map/mapwindow.py
Fix center based recalculations to be based on both center or zoom changes.
Add get_map_base() method, for possible future use.
Add attempt at zoom specific point plotting corrections so that
the position reported by my GPS is plotted correctly on the map.
d_rats/maptile.py:
Add some properties to the MapTile class to try to eliminate fudge factors.
For set_map_info method, map_url_key no longer optional.
Fix deg2num method to be inverse of num2deg method.
Add deg2tile method to return the map tile.
Add deg2pixel method as an attempt to return a pixel coordinate.
Handle math overflow in num2deg method.
Fix to handle odd error, or possible threading race condition where
os.path.isdir returns that a directory does not exist, yet os.makedirs
fails because the directory …
> Attempt to improve point plotting on map

- d_rats/spell.py
d_rats/spell.py:
Make Gtk.TextTag use new method to create to match
other usage in d-rats
> Fix Gtk.TextTag in spell module

- d_rats/mainapp.py
Detect and issue an error message for when internationalization
has not been setup.
In the _refresh_lang method diagnose when message catalog is missing.
Add some comments for future triggering of map redraw when
the map provider is changed.
> mainapp gettext fix

- d_rats/map/mapdraw.py
- d_rats/map/maptile.py
- d_rats/map/mapwidget.py
Added the info window functionality.
Finally found the way to convert between display coordinates and
point positions with out using fudge factors.
Fixed up minor issues with marker display.
remove unused get_map_base method.
Move calculating map to display offset to MapTile class.
In draw_image_at method, center icon over point.
in draw_marker method, use Map.Tile.deg2display() instead of latlon2xy.
In draw_marker method, remove fudge factor usage.
in draw_text_marker_at method, Make sure text is centered on point.
In expose_map method, refactor to use MapTile methods to reduce
code duplication in other methods.
Add _set_x_origin method to calculate and store display origin as
a class variable.
Add get_display_center as a class method, as a …
> Add Info Window, Remove fudge factor.

- d_rats/dplatform.py
wb8tyw_issue: 71
The Win32com.shell functions can return bytes instead of str type.
For python3, those values must be decoded into str type.
Fix broad-exceptions for Win32 methods
In Win32Platform.gui_select_dir return path as a str.
> fix(dplatform) Win32Platform Python 3 fixes

- d_rats/config.py
- d_rats/miscwidgets.py
- ui/addport.glade
wb8tyw_issue: 63
In DratsPanel.make_view method, set panel to fill the width
of the container.
In class KeyedListWidget, set the view to fill the width of
the container.
In class KeyedListWidget _make_view method, fix field expansion.
ui/addport.glade:
set some field widths for radio entries.
> fix(config) Improve Config settings

- d_rats/spell.py
d_rats/spell.py:
In Spelling.lookup_word method, set logging to debug.
In the __do_fly_spell function, fix buffer.get_text call
> fix(spell) Fix spell checking

- d_rats/map/mapdraw.py
- d_rats/map/maptile.py
A Gtk Widget call can not be made inside of a Python Thread.
In expose_map method, pass widget reference, not a callback.
Throttle queuing map draw events on tile updates
When a threaded fetch completes, it now adds a delayed
map queue event, if there is not one pending.
Note this delayed event does not actually seem to be needed
as the map seems to update just before the event is queued.
> fix(map) Fix tile threading

- d_rats/dplatform.py
In Win32Platform.gui_select_dir, catch a pywintypes.com_error
that was seen on Windows 10 when no directory was selected.
> fix(dplatform): Fix unhandled win32 exception

- d_rats/comm.py
- d_rats/dplatform.py
Make sure serial radio and TNC modes work.
Convert to python3.
Fix some broad exceptions.
Fix DTR and RTS to be set according to standards.
in kiss_recv_frame module, discard the 2 fcs check bytes.
Fix handling of exception when serial port is in use.
> fix:(comm): TNC and Serial Port fixes

- d_rats/sessions/file.py
- d_rats/ui/main_files.py
Make sure endian is when using integers with pack or unpack or
transfers will not work on all platforms.
Have to specify little-endian here to be compatible with most of
the existing d-rats deployments, even though the normally
big endian would be used for a network.
d_rats/sessions/file.py:
Need to explictly specify endian for integers transferred over the
Network.
Fix a typo that broke file transfers.
> fix:(file) Fix file transfers

- d_rats/agw.py
- d_rats/comm.py
- d_rats/dratsexception.py
- d_rats/transport.py
I do not have an AGWPE driver, so this is the best that I can do
using the existing code, the AGWPE developer documentation and a
simple loopback test server for now.
Based on what I found in testing, I do not think I made it any worse
that what it was, but maybe it will help someone else with the
actual AGWPE driver fix anything that I missed.
d_rats/agw.py:
Fix a lot of pylint diagnostics.
Converted to match current AGWPE documentation.
Fix structures to use little-endian explicitly.
Python3 compatible bytes usage.
In AGWConnection.recv_frame method,
fix to receive the entire frame instead of just the header.
Add simple test server for simple sanity tests.
Move exceptions into d_rats/dratsexeceptions.py for agw.py also to …
> fix:(comm) Attempt to fix AGWPE

- d_rats/ax25.py
Convert currently unused ax25 module to python3.
d_rats/ax25.py:
Python3 conversion.
Add Docstrings.
> fix:(ax25) Convert ax25 module to python3

- d_rats/callsigns.py
Convert currently unused Callsigns module to python3.
d_rats/callsigns.py:
Add Docstrings.
Resolve pylint issues.
> fix (callsings) Convert Callsigns to python3

- libexec/lzhuf.h
lzhuf.h:
Add missing include of errno.h
Remove dangerous commented out code to hack around missing include.
> fix(lzhuf): Fix lzhuf.h header file

- d_rats/wl2k.py
Catch specific exceptions.
Raise module specific named exceptions.
Remove some unused code.
> fix(wl2k): Fix exception handling

- d_rats/agw.py
- d_rats/sessions/rpc.py
- d_rats/sessions/sniff.py
- d_rats/version.py
- d_rats/wl2k.py
The w2lk stuff depends a bit on e-mail, which has not yet been
verified as working on python3.
d_rats/agw.py:
Remove extra diagnostic logging message
Whitespace fix
d_rats/sessions/sniff.py:
Fix deprecated GObject.SIGNAL_RUN_LAST
Add DRATS_VERSION_NUM to comply with w2lk restrictions on
version numbering.
Convert to python3.
Add simple test server.
> fix(w2lk): Attempt to get w2lk working

- d_rats/wl2k.py
Some bugfixes for issues found in testing and by running pylint3 from
the command line.
The pylint built into Visual Studio Code missed some issues.
in run_lzhuf method, subprocess.mswindows property
has been removed.
In ssid method, actually pass the ssid.
In get_proposal method, actually return the proposal.
> fix(wl2k): Bug fixes for wl2k

- d_rats/emailgw.py
- d_rats/formgui.py
- d_rats/mailsrv.py
- d_rats/mainapp.py
- d_rats/ui/main_messages.py
Get the mailsrv module working with Python 3
d_rats/emailgw.py:
Remove some python2 compatibility code.
Fix gettext import for pylance warnings.
Only fixed sections used by mailsrv.
d_rats/formgui.py:
Fix FormFile.get_xml() method.
d_rats/mailsrv.py:
Convert to printlog.
Convert to use bytes type were needed.
Corrected invalid names for mailsrv classes.
> fix(mailsrv) Get Mailsvr module working

- d_rats/mainapp.py
- d_rats/map_sources.py
- d_rats/msgrouting.py
- d_rats/qst.py
- d_rats/session_coordinator.py
- d_rats/sessions/chat.py
- d_rats/sessions/rpc.py
- d_rats/ui/main_chat.py
- d_rats/ui/main_events.py
- d_rats/ui/main_files.py
- d_rats/ui/main_messages.py
- d_rats/wl2k.py
d_rats/msgrouting.py:
d_rats/qst.py:
d_rats/session_coordinator.py:
d_rats/sessions/chat.py:
Use GLib.idle_add instead.
> fix(GLib): GOobject.idle_add deprecated

- d_rats/wl2k.py
Set explicit endian for struct pack, especially since w2lk uses
little-endian instead of network-endian.
In _run_outgoing() method, message header must be parsed as bytes and
parsed data must be converted to strings.
> fix(w2lk): bytes to string conversions

- d_rats/gps.py
- d_rats/mainapp.py
- d_rats/map/mapwindow.py
- d_rats/qst.py
- d_rats/sessions/rpc.py
- docs/source/d_rats.rst
Fix names to match current python conventions
d_rats/gps.py:
rename methods to current python conventions.
d_rats/qst.py:
rename methods from gps.py to new names.
docs/source/d_rats.rst:
remove d_rats.subst from document list
> fix(gps) Fix invalid names

- d_rats/dplatform.py
- d_rats/map/mapwindow.py
- d_rats/pluginsrv.py
- d_rats/wu.py
- docs/source/d_rats.rst
Fix issues with document generation.
The run_sync method should return str, not bytes to be
consistent on all platforms.
d_rats/map/mapwindow.py
Docstring fixes and improvements.
d_rats/pluginsrv.py:
d_rats/wu.py:
Docstring fix.
docs/source/d_rats.rst:
Remove entry for platform module.
> fix(doc): Documentation fixes

- d_rats/sessionmgr.py
- d_rats/sessions/base.py
- d_rats/sessions/rpc.py
- d_rats/sessions/stateful.py
d_rats/sessionmgr.py:
Remove python2 compatibility code.
Fix name conflict for RPC notify_event().
Remove a broad exception
d_rats/sessions/base.py:
Remove python2 compatibility code.
The notify method name conflicts with child class inherited GObject
notify method name in rpc.py, change name to notify_event.
Remove python2 compatibility code.
The notify method name conflicts with inherited GObject
notify method name, change name to notify_event.
Improve DocStrings
Fix invalid method names.
d_rats/sessions/stateful.py:
The notify method name conflicts with inherited GObject
notify method name in rpc.py, change name to notify_event.
> fix(rpc): Code cleanup

- d_rats/pluginsrv.py
- d_rats/sessions/rpc.py
- d_rats/utils.py
- docs/source/modules.rst
- docs/source/plugin_test.rst
- plugin_test.py
Starting to standardize on using variable name of stationid for
a callsign with a dash suffix to avoid confusion.
d_rats/pluginsrv.py:
Change to use stationid.
Fix lookup of RPC modules.
Fix spelling error in Docstrings.
Renamed port_for_station to port_for_stationid.
docs/source/modules.rst
Add plugin_test module
docs/source/plugin_test.rst: New Module.
plugin_test.py: New module.
Start of a module to fully test the pluginsrv module.
> fix(pluginsrv) pluginsrv module

- d_rats/mainapp.py
The methods in run_gtk_locked function have been deprecated,
so the run_gtk_locked decorator is no longer needed.
Remove run_gtk_locked decorator.
> fix(mainapp): Remove deprecated run_gtk_locked

- d_rats/emailgw.py
The periodic polling for the emailgw is just flooding th console log.
Change to debug for now.
d_rats/emailgw.py:
Move the log level for emailgw to debug
> fix(emailgw): set log level debug

- d_rats/formbuilder.py
- d_rats/mainwindow.py
- docs/source/d_rats.map.rst
- ui/mainwindow.glade
Need to convert to Gtk.ApplicationWindow as a first step of
migrating to the new supported menu APIs.
d_rats/formbuilder.py:
Convert to use a Gtk.ApplicationWindow.
Convert for using Gtk.ApplicationWindow.
ui/mainwindow.glade:
Convert mainwindow to Gtk.ApplicationWindow.
docs/source/d_rats.map.rst:
Remove non-existent maptilecontext entry.
> fix(application): Gtk.ApplicationWindow

- d_rats/ui/main_chat.py
- d_rats/ui/main_common.py
- d_rats/ui/main_events.py
- d_rats/ui/main_files.py
- d_rats/ui/main_messages.py
- d_rats/ui/main_stations.py
More code cleanup to be closer to current Python conventions.
d_rats/ui/main_common.py:
d_rats/ui/main_stations.py:
Fix lookup of menu tab text from glade file.
> fix(ui_main) code cleanup

- d_rats/mainwindow.py
- d_rats/ui/main_chat.py
- d_rats/ui/main_common.py
- d_rats/ui/main_events.py
- d_rats/ui/main_files.py
- d_rats/ui/main_messages.py
- d_rats/ui/main_stations.py
The new Gio menu system needs access to the Gtk.ApplicationWindow
object of the mainWindow object.
Pass Gtk.ApplicationWindow object as optional parameter.
Update the unit test to do something.
d_rats/ui/main_common.py:
Fix up MainWindowElement and MainWindowTab classes For
handling optional prefix and window parameters.
d_rats/ui/main_stations.py:
Fix up for API change.
> fix(main_common): API change

- d_rats/ui/event_popup_model.py
- d_rats/ui/event_tab.py
- d_rats/ui/message_list.py
- docs/source/d_rats.ui.rst
Implement the Mouse Popup Menu for events.
d_rats/ui/event_popup_model.py:
New module for EventPopupModel class.
d_rats/ui/event_tab.py:
Use EventPopupModel to implement mouse popup menu.
d_rats/ui/message_list.py:
Fix broken Docstrings.
docs/source/d_rats.ui.rst:
Add new modules for message and event classes.
> fix(main_event): Implement popup menu

- d-rats.py
- d-rats_repeater.py
- d_rats/dplatform.py
Fix setting the config directory option
d-rats.py:
d-rats_repeater.py:
Use new platform set_base_dir method.
Code Cleanup to be closer to current Python conventions.
Add set_base_dir method to allow changing the base directory.
Remove python2 compatibility code.
> fix(option): Fix config option

- d_rats/sessions/rpc.py
- d_rats/ui/account_dialog.py
- d_rats/ui/event_popup_model.py
- d_rats/ui/main_stations.py
- d_rats/ui/message_popup_model.py
- docs/source/d_rats.ui.rst
Convert to current python programming conventions.
d_rats/ui/account_dialog.py:
Refactored from d_rats/ui/main_station.py into a class.
d_rats/ui/main_stations.py:
Refactor account dialog into its own module.
Refactor code to remove pylint diagnostics
Pass account object instead of many parameters.
d_rats/ui/event_popup_model.py:
d_rats/ui/message_popup_model.py:
Fix comments
docs/source/d_rats.ui.rst:
Add d_rats/ui/account_dialog to documentation generation.
> fix(main_station): Code cleanup

- d_rats/ui/main_stations.py
- d_rats/ui/station_popup_model.py
- docs/source/d_rats.ui.rst
Update to use supported Gio.Menu API.
Unfortunately, at least for now, we lose the icons in the menu.
d_rats/ui/main_stations.py:
Change to use Gio.Menu API.
d_rats/ui/station_popup_model.py:
New module for creating Popup Model for Menu.
docs/source/d_rats.ui.rst:
Add d_rats/ui/station_popup_model.py to documentation.
> fix(main_stations): Update to Gio.Menu

- d_rats/mainwindow.py
- d_rats/ui/main_chat.py
Convert mainwindow.py to current python programming conventions.
Move self.logger to be a class variable.
Change hidden protected __window property to just be protected.
Use new ChatTab.display_info method for startup messages.
Refactor handler functions into their own methods.
Add display_info method.
> fix(mainwindow): Code cleanup

- d_rats/mainwindow.py
- d_rats/menu_helpers.py
- d_rats/ui/main_chat.py
- d_rats/ui/message_popup_model.py
- d_rats/ui/station_popup_model.py
- docs/source/d_rats.rst
- ui/mainwindow.glade
d_rats/menu_helpers.py:
New modules for functions to update glade generated
menu items with Icons.
Fix crash on exit.
Add themed images to replace stock images.
Add themed images to replace stock images.
docs/source/d_rats.rst:
Add d_rats/menu_helpers.py
ui/mainwindow.glade:
Replace GtkImageMenuItem with GtkMenuItem.
d_rats/ui/message_popup_model.py:
d_rats/ui/station_popup_model.py:
Set up to use themed icons.
Themed icons still are not working.
> Fixes for deprecated menu APIs.

- d_rats/map_sources.py
- d_rats/miscwidgets.py
- d_rats/sessions/control.py
- d_rats/sessions/file.py
- d_rats/sessions/stateful.py
- d_rats/ui/main_chat.py
- d_rats/utils.py
d_rats/sessions/control.py:
d_rats/sessions/file.py:
d_rats/sessions/stateful.py:
Remove six.moves imports and references.
> fix(python3): Remove remaining six.moves imports

- d-rats.py
- d_rats/dplatform.py
d-rats.py:
Set the platform_config_dir, it is not a base dir.
Fix the system data path to use the standard locations
instead of a hardcoded one that does not work for
installing from pip into a virtual environment.
Change set_base_dir to set_config_dir to remove confusion.
Start deprecation of get_source method.
Add method to get the constant d-rats data.
> fix(dplatform): Fix system data paths

- MANIFEST.in
- NEWS.rst
- README.md
- changelog
- changes/100.bugfix
- changes/115.bugfix
- changes/121.misc
- changes/124.bugfix
- changes/125.misc
- changes/134.feature
- changes/135.bugfix
- changes/202.bugfix
- changes/204.feature
- changes/245.feature
- changes/246.bugfix
- changes/247.feature
- changes/254.bugfix
- changes/73.bugfix
- install.txt
- libexec/makefile
- msys2_packages.sh
- newsfragments/.gitignore
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
Now use python -m build and towncrier for building packages.
MANIFEST.in:
Updated list of files.
NEWS.rst:
Start of NEWS.rst.
README.md:
Update for new packaging documentation.
changelog:
Note the change to NEWs.rst based on towncrier.
changes/: (new)
Changes for a future NEWS.rst generated for a release.
libexec/makefile:
Fix make clean to work on most platforms.
msys2_packages.sh: (new)
Script to help install packages on msys2 for Microsoft Windows.
newsfragments/.gitignore: (new)
Directory that towncrier said to create apparently used
just for temporary files.
pyproject.toml: (new)
Description file for d-rats project.
requirements.txt: (new)
Needed packages for building python packages in a virtual
envrionment.
setup.cfg:
Comment out until disto packaging is figured out.
setup.py: …
> fix(packaging): New packaging method

- README.md
- tests/pre-commit
- tests/pre-commit_d/pylint_check.sh
Add a pre-commit hook and a pylint check.
This is to catch errors that were missed in testing before
you commit a change.
More checks will be added in the future.
Use 'cp tests/pre-commit .git/hooks' to activate.
Make sure that you have execute accss to the file, on Linux
that should already be the case.
tests/pre-commit: (New file)
A pre-commit hook to be copied into .git/hooks
tests/pylint_check.sh:
A pylint checking script
> fix(tests) Add pre-commit hook

- .github/workflows/xmllint.yml
- README.md
- msys2_packages.sh
- tests/install_xmllint_ubuntu.sh
- tests/pre-commit_d/codespell_check.sh
- tests/pre-commit_d/pylint_check.sh
- tests/pre-commit_d/shellcheck_check.sh
- tests/pre-commit_d/xmllint_check.sh
tests/install_xmllint_ubuntu.sh: (new)
Script to install xmllint for a github action.
tests/pre-commit_d/xmllint_check.sh: (new)
Git hook to scan for xml files.
README.md:
add libxml2-utils to list of packages
msys2_packages.sh:
Add codespell to development packages
tests/pre-commit_d/codespell_check.sh:
tests/pre-commit_d/pylint_check.sh:
tests/pre-commit_d/shellcheck_check.sh:
Do not fail pre-commmit if linting tool is not present.
> fix(xmllint) Add xmllint checklist
